### ISSUE TITLE
A11Y: headings contrast or spacing and footer contrast

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#4625]
For example: https://exercism.io/become-a-maintainer

## Headings
This might depends on OS + Browser combination (as exercism uses system-fonts (yay!)), but the current way the headings are set up makes it hard to know where the header ends and the text start and which paragraphs belong where:

![image](https://user-images.githubusercontent.com/1964376/51543611-3f57f980-1e5e-11e9-81b6-2fd5bb15c03f.png)

Consider increasing the margin between a paragraph and the next heading, or easier, upping the font-weight by a hundred:

![image](https://user-images.githubusercontent.com/1964376/51543709-78906980-1e5e-11e9-8a0c-4c85d26a01e0.png)

Further more, the `h2` and `h3` have the same size:

![image](https://user-images.githubusercontent.com/1964376/51543791-ad9cbc00-1e5e-11e9-90e3-d311f32ab1de.png)

Whereas these are actually supposed to look something like this:

![image](https://user-images.githubusercontent.com/1964376/51543815-bd1c0500-1e5e-11e9-8bc6-9277d56a89e1.png)

```CSS
#generic-page h2 {
  font-size: 22px;
}

#generic-page h3 {
  font-size: 18px;
}

#generic-page h2, #generic-page h3 {
    line-height: 18px;
    font-weight: 500;
    margin: 30px 0 10px 0
}
```

## Footer
The links in the footer are not legible. It's below normal-size and the color combination `#aaaaaa`/`#fafafa` has a contrast ratio of 2.23, which is [not sufficient](https://a11yproject.com/posts/what-is-color-contrast/). At this size, it needs a ratio of at least *4.5*.

Consider using the `#737373` on top of the background of `#fafafa`  which has a contrast ratio of 4.54 

```CSS
footer .legal .copyright,footer .legal a,footer .legal .created-by {
    color: #737373;
    font-size: 13px;
    line-height: 15px;
    display: inline-block
}
```
