### ISSUE TITLE
Add GitHub Action to triage issues

### ISSUE THREAD

**Issue by iHiD** [exercism/exercism#5058]
I'd like a GitHub Action added where I could leave a comment with: `/triage to support` and that would move the issue to `exercism/support`. It should work for any repo that exists, and for anyone that has `triage` permissions on this repo. The only barrier might be that I'm not sure "Move issue" has an API end point yet.

Does anyone want to volunteer to investigate/write/do this?

**Comment by sshine** [comment]
@NobbZ: Thanks for clarifying the need.

@vanntile: Excellent initial research.

@iHiD: You're right. We could even do the thing where applying "type/support" automatically moves it to exercism/support and reapplies the appropriate labels.

**Comment by vanntile** [comment]
@sshine I'll work further on creating a GitHub Action that offers the necessary things for the below script, but this is the basic query we'll need for transferring the issue:

```js
require('isomorphic-fetch');

const mutation = ' \
mutation { \
    transferIssue(input: { \
      clientMutationId: TOKEN, \
      repositoryId: "MDEwOlJlcG9zaXRvcnkyMTI0MTE5ODY=", \
      issueId: "MDU6SXNzdWU1MDE2NjIzODg=" \
    }) { \
      clientMutationId \
    } \
  } \
'

fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'Authorization': "token TOKEN",
    },
    body: JSON.stringify({ query: mutation }),
})
    .then(res => res.json())
    .then(res => console.log(res));
```

**Comment by iHiD** [comment]
@iHiD: You're right. We could even do the thing where applying "type/support" automatically moves.

Yep - that'd be really nice!

**Comment by vanntile** [comment]
@iHiD I've come to the conclusion that this automation is beyond myself. Two distinct paths I recommend the next one who can grab this issue are:

1) [https://github.com/helaili/github-graphql-action](https://github.com/helaili/github-graphql-action)
2) A Node Action that executes something similar to this (a customised version on the default node Action:

```yml
name: Node CI

on:
  issue_comment:
    types: [created, edited]  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 12.x

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
        TOKEN: ${{ secrets.TOKEN }} # Or as an environment variable
```
