### ISSUE TITLE
Homepage is horizontally scrollable

### ISSUE THREAD

**Issue by TimonVS** [exercism/exercism#6271]
The homepage shows a horizontal scrollbar, because of an image.

The following suggestions will probably fix the issue:

- Change CSS of main graphic:

```css
#page-landing section.mentoring-section .main-graphic {
  margin-left: auto;
  margin-right: auto;
  width: 100%;
  max-width: 100%;
}
```
- Add `width` and `height` attributes to `img` element [to preserve aspect ratio and to prevent layout shift](https://developer.mozilla.org/en-US/docs/Web/Media/images/aspect_ratio_mapping).

## Screenshots

![CleanShot 2022-03-06 at 15 16 36@2x](https://user-images.githubusercontent.com/876666/156927109-ea645fae-4684-4471-9ecf-97ccb3af3d65.png)

![CleanShot 2022-03-06 at 15 16 31@2x](https://user-images.githubusercontent.com/876666/156927124-72198b57-4e6d-4009-90ad-04ab5fd277d8.png)
