### ISSUE TITLE
Update with author face looks like link but isn't

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/exercism#6305]
![image](https://user-images.githubusercontent.com/1964376/159980058-fc80e14e-a7fd-4ead-9712-7fcd3e984395.png)

When hovering, due to the following CSS, it looks like I can click it:

```css
.c-faces .face {
  cursor: pointer;
  transition: margin .2s ease-out;
}
```
