### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by a12l** [exercism/exercism#6346]
When I submit my solution to a Haskell exercise, I get an error message in the `Tests` tab.

The solution works flawlessly on my computer, and the library's source code hasn't changed in two years.

```
Cabal file info not found for multiset-0.3.4.3@sha256:968192524bd38ffa29856e1e3f9f6f8a5704f98899d4b25f8ebd425001594f61,1790, updating
Selected mirror https://hackage.haskell.org/
Downloading root
HttpExceptionRequest Request {
  host                 = "hackage.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding",""),("User-Agent","Haskell pantry package")]
  path                 = "/root.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "hackage.haskell.org", service name: Just "443"): does not exist (Try again))
```

My `package.yaml` file

```
name: anagram
version: 1.4.0.8

dependencies:
  - base
  - text
  - containers
  - multiset

library:
  exposed-modules: Anagram
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - anagram
      - hspec
```

The library's Cabal file is can be found here: https://github.com/twanvl/multiset/blob/master/multiset.cabal, and the library is listed on Hackage here: https://hackage.haskell.org/package/multiset
